### ISSUE TITLE
Taunt Spam

### ISSUE THREAD

**Issue by jmd7231** [therealist/PH_BetterTauntMenu#1]
Hello I noticed this is a really great addon and I appreciate you sharing it however i noticed people on my server spamming taunts that last long. Is there a way to make it so when they use a taunt the button goes away for like 5 mins? or if they use more than idk like 5 taunts its comes back? Other than that this is a great!

**Comment by therealist** [comment]
I did not see this open ticket until I went to update it now. Lots of changes have been made, including what you suggested about removing buttons as the taunts are played.
